spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: "mySecretKeyForAiChatBotApplicationThatShouldBeAtLeast256BitsLongForSecurity2024"
  expiration: 86400000

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: "https://api.openai.com/v1"
    model: "gpt-3.5-turbo"
    max-tokens: 2000
    temperature: 0.7